services:
  - type: web
    name: agentic-rag-rust-core
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_HTTP_REFERER
        value: https://example.com
      - key: OPENROUTER_TITLE
        value: Agentic-RAG-Rust-Core-PFE-26
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: HF_TOKEN
        sync: false
